//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desafio
    {
        public int Id { get; set; }
        public string IDDesafiante { get; set; }
        public string IDDesafiado { get; set; }
        public Nullable<int> IDDificuldade { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<int> IDPalavra { get; set; }
        public string Resultado { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
